message_attributes = [
  { positive: false, text: 'Better luck next time.' },
  { positive: false, text: 'You can do better.' },
  { positive: false, text: 'Come on!!' },
  { positive: false, text: 'Come back strong.' },
  { positive: false, text: 'Hmm... very bad!' },
  { positive: false, text: 'It is not good!' },
  { positive: false, text: 'karmayogi hates you!' },
  { positive: false, text: 'Learn something from this.' },
  { positive: false, text: 'Nevermind.' },
  { positive: false, text: 'Oh my god!' },
  { positive: false, text: 'Really?' },
  { positive: false, text: 'This is bad.' },
  { positive: false, text: 'This is cruelty.' },
  { positive: false, text: 'This should not be happening.' },
  { positive: false, text: 'Why?' },
  { positive: false, text: 'You deserve it.' },
  { positive: false, text: 'You know what you did.' },
  { positive: true, text: 'All is well.' },
  { positive: true, text: 'All the best.' },
  { positive: true, text: 'Are you Batman?' },
  { positive: true, text: 'Awesome one.' },
  { positive: true, text: 'Good one.' },
  { positive: true, text: 'Great one.' },
  { positive: true, text: 'Hurray!' },
  { positive: true, text: 'karmayogi likes you!' },
  { positive: true, text: 'Keep rocking.' },
  { positive: true, text: 'There are no words to describe how awesome you are.' },
  { positive: true, text: 'Party!' },
  { positive: true, text: 'You are an inspiration.' },
  { positive: true, text: 'You are great!' },
  { positive: true, text: 'You are the sailor!' },
  { positive: true, text: 'You deserve it.' },
  { positive: true, text: 'You rock!' },
  { positive: true, text: 'Well done!' },
]

message_attributes.each do |attributes|
  Message.create(attributes) unless Message.where(attributes).first
end
